name: Docker img
on:
  push:
    branches:
    - master
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Build
      run: |
        cd ./scripts
        docker build --tag johnel/package-builder:latest .
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push
      run: docker push johnel/package-builder
