name: Build packages
on:
  push:
    branches: pmaster
  workflow_dispatch:
jobs:
  build-for-arm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run:
        chmod +x Foo.sh
        ./scripts/run-docker.sh bash -c "./build-package.sh -I -a arm toboe"
    - name: release
      run: |
        echo "done"
        gh release create ${{ github.run_number}}.0.0 ./output/*
      env:
        GITHUB_TOKEN: ${{ secrets.TK }}
      shell: bash
