name: Build packages
on:
  push:
    branches: pmaster
  workflow_dispatch:
jobs:
  build-for-arm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        john_package_name="pdfmium_viewer" #john_package_name="tesseract"
        chmod +x pre_conf_build.sh
        ./pre_conf_build.sh "$john_package_name"
        ./scripts/run-docker.sh bash -c "./build-package.sh -a arm $john_package_name"
    - name: release
      run: |
        echo "donei"
        gh release create ${{ github.run_number}}.0.0 ./output/*
      env:
        GITHUB_TOKEN: ${{ secrets.TK }}
      shell: bash

