name: Build packages
on:
  push:
    branches: pmaster
  workflow_dispatch:
jobs:
  build-for-arm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: ./scripts/run-docker.sh bash -c "./build-package.sh -I -a arm toboe && sudo apt-get install openjdk-21 && jlink --module-path $JAVA_HOME/jmods --add-modules java.base --output output/custom-jre"
    - name: release
      run: |
        echo "done"
        gh release create ${{ github.run_number}}.0.0 ./output/*
      env:
        GITHUB_TOKEN: ${{ secrets.TK }}
      shell: bash
