name: Build packages
on:
  push:
    branches: master

jobs:
  build-for-arm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    #- run: sudo apt install libc6-dev
    - run: sudo ./scripts/run-docker.sh
    - run: |
        pwd
        ls ../..
        ls /home/runner
        ls /usr -a
    # - run: sudo apt install openjdk-17-jdk
    # - run: |
    #     sudo ./scripts/setup-android-sdk.sh
    # - run: sudo ./build-package.sh -a arm lisdir
    # - run: ls -a
    # - run: ls ./output/
    # - name: release
    #   run: |
    #     gh release create ${{ github.run_number}}.0.0 ./output/*
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.TK }}
    #   shell: bash
   
