name: Build packages
on:
  push:
    branches: master

jobs:
  build-for-arm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo ./scripts/run-docker.sh
    - run: sudo apt install openjdk-8-jdk
    - run: sudo ./scripts/setup-android-sdk.sh
    - run: sudo ./build-package.sh -a arm vim
    - run: ls -a
    - run: ls ./output/
    - uses: actions/upload-artifact@v3
      with:
        name: upload debs
        path: ./output
