name: Build packages
on:
  push:
    branches: master

jobs:
  build-for-arm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt install libc6-dev
    - run: ./scripts/run-docker.sh ./build-package.sh -a arm lisdir
    
    # - run: sudo apt install openjdk-17-jdk
    # - run: |
    #     sudo apt install nlohmann-json3-dev
    #     sudo ./scripts/setup-android-sdk.sh
    - run: ls -a
    - run: ls ./output/
    - name: release
      run: |
        gh release create ${{ github.run_number}}.0.0 ./output/*
      env:
        GITHUB_TOKEN: ${{ secrets.TK }}
      shell: bash
   
