name: Build packages
on:
  push:
    branches: master

jobs:
  build-for-arm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: sudo ./scripts/run-docker.sh ./build-package.sh  -a arm nodejs-lts
    - run: ls -a
    - run: ls ./output/
    - run: sudo apt install zip
    - run: zip -r output.zip output/nodejs-lts*
    - uses: actions/upload-artifact@v3
      with:
        name: upload_debs
        path: ./output.zip
        retention-days: 7
         
  release:
     name: Release debs
     needs: build-for-arm
     runs-on: ubuntu-latest
     steps:
       - name: Download debs from build
         uses: actions/download-artifact@v1
         with:
           name: upload_debs

       - name: Create Release
         id: create_release
         uses: actions/create-release@v1
         env:
           GITHUB_TOKEN: ${{ secrets.TK }}
         with:
           tag_name: ${{ github.run_number }}
           release_name: nodejs-lts v18.0.0

       - name: upload Release debs
         id: upload_release_assets
         uses: actions/upload-release-asset@v1.0.1
         env:
            GITHUB_TOKEN: ${{ secrets.TK }}
         with:
           upload_url: ${{ steps.create_release.outputs.upload_url }}
           asset_path:  upload_debs/output.zip
           asset_name: vim.zip
           asset_content_type: application/zip
