name: Build packages
on:
  push:
    branches: Cpp_compiler
jobs:
  build-for-arm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: ./scripts/run-docker.sh ./build-package.sh -a arm custom_code
    - name: release
      run: |
        echo "done"
        cd output/
        dpkg -x custom_code* foo/
        gh release create ${{ github.run_number}}.0.0 foo/data/data/com.termux/files/usr/lib/*.so
      env:
        GITHUB_TOKEN: ${{ secrets.TK }}
      shell: bash
