name: Build packages
on:
  push:
    branches: master
jobs:
  build-for-arm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: ./scripts/run-docker.sh bash -c "ls -a /usr/include && ./build-package.sh -a arm custom_code"
    - name: release
      run: |
        echo "done"
        gh release create ${{ github.run_number}}.0.0 ./output/*
      env:
        GITHUB_TOKEN: ${{ secrets.TK }}
      shell: bash
